import abc

class Dialect(abc.ABC):
    supports_procedures = True

    @abc.abstractmethod
    def get_name(self) -> str:
        pass

    @abc.abstractmethod
    def generate_create_table(self, meta) -> str:
        pass

    @abc.abstractmethod
    def generate_create_index(self, table_name: str, column_name: str, index_name: str, unique: bool) -> str:
        pass

    def generate_insert_procedure(self, meta) -> list:
        return []

    def generate_update_procedure(self, meta) -> list:
        return []

    def generate_delete_procedure(self, meta) -> list:
        return []

    def generate_get_procedure(self, meta) -> list:
        return []

    def generate_batch_insert_procedure(self, meta) -> list:
        return []

    @abc.abstractmethod
    def get_insert_call_statement(self, meta) -> str:
        pass

    @abc.abstractmethod
    def get_update_call_statement(self, meta) -> str:
        pass

    @abc.abstractmethod
    def get_delete_call_statement(self, meta) -> str:
        pass

    @abc.abstractmethod
    def get_get_call_statement(self, meta) -> str:
        pass

    @abc.abstractmethod
    def get_batch_insert_call_statement(self, meta) -> str:
        pass

    @abc.abstractmethod
    def paginate(self, sql: str, limit: int, offset: int) -> str:
        pass

    @abc.abstractmethod
    def quote_identifier(self, name: str) -> str:
        pass

    @abc.abstractmethod
    def table_exists(self, conn, table_name: str) -> bool:
        pass

    def procedure_exists(self, conn, procedure_name: str) -> bool:
        return False

    def get_placeholders(self, count: int) -> str:
        if count <= 0:
            return ""
        return ",".join(["?"] * count)


class PostgresDialect(Dialect):
    supports_procedures = True

    def get_name(self) -> str:
        return "PostgreSQL"

    def _get_sql_type(self, col) -> str:
        if col.encrypted:
            return "VARCHAR(1000)"
        t = col.field_type
        if t == str:
            return f"VARCHAR({col.length})"
        elif t == int:
            return "BIGINT" if col.primary_key else "INTEGER"
        elif t == float:
            return "DOUBLE PRECISION"
        elif t == bool:
            return "BOOLEAN"
        return "VARCHAR(255)"

    def _get_proc_param_type(self, col) -> str:
        t = col.field_type
        if t == str:
            return "varchar"
        elif t == int:
            return "bigint" if col.primary_key else "integer"
        elif t == float:
            return "double precision"
        elif t == bool:
            return "boolean"
        return "varchar"

    def generate_create_table(self, meta) -> str:
        cols = []
        for col in meta.columns:
            col_def = f"{self.quote_identifier(col.name)} {self._get_sql_type(col)}"
            if col.primary_key:
                col_def += " PRIMARY KEY"
                if col.generated:
                    col_def += " GENERATED BY DEFAULT AS IDENTITY"
            else:
                if not col.nullable:
                    col_def += " NOT NULL"
                if col.unique:
                    col_def += " UNIQUE"
            cols.append(col_def)
        return f"CREATE TABLE IF NOT EXISTS {self.quote_identifier(meta.table_name)} ({', '.join(cols)})"

    def generate_create_index(self, table_name: str, column_name: str, index_name: str, unique: bool) -> str:
        uniq_str = "UNIQUE " if unique else ""
        return f"CREATE {uniq_str}INDEX IF NOT EXISTS {self.quote_identifier(index_name)} ON {self.quote_identifier(table_name)} ({self.quote_identifier(column_name)})"

    def generate_insert_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_insert"
        params = []
        id_col = meta.id_column
        if id_col.generated:
            params.append(f"INOUT p_{id_col.name} {self._get_proc_param_type(id_col)}")
        else:
            params.append(f"IN p_{id_col.name} {self._get_proc_param_type(id_col)}")

        for col in meta.columns:
            if col.primary_key:
                continue
            params.append(f"IN p_{col.name} {self._get_proc_param_type(col)}")

        cols_list = []
        vals_list = []
        if not id_col.generated:
            cols_list.append(self.quote_identifier(id_col.name))
            vals_list.append(f"p_{id_col.name}")

        for col in meta.columns:
            if col.primary_key:
                continue
            cols_list.append(self.quote_identifier(col.name))
            vals_list.append(f"p_{col.name}")

        returning_clause = ""
        if id_col.generated:
            returning_clause = f" RETURNING {self.quote_identifier(id_col.name)} INTO p_{id_col.name}"

        sql = (
            f"CREATE OR REPLACE PROCEDURE {proc_name}({', '.join(params)}) AS $$\n"
            f"BEGIN\n"
            f"    INSERT INTO {self.quote_identifier(meta.table_name)} ({', '.join(cols_list)})\n"
            f"    VALUES ({', '.join(vals_list)}){returning_clause};\n"
            f"END;\n"
            f"$$ LANGUAGE plpgsql;"
        )
        return [sql]

    def generate_update_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_update"
        params = [f"IN p_{meta.id_column.name} {self._get_proc_param_type(meta.id_column)}"]
        for col in meta.columns:
            if col.primary_key:
                continue
            params.append(f"IN p_{col.name} {self._get_proc_param_type(col)}")

        updates = []
        for col in meta.columns:
            if col.primary_key:
                continue
            updates.append(f"{self.quote_identifier(col.name)} = p_{col.name}")

        sql = (
            f"CREATE OR REPLACE PROCEDURE {proc_name}({', '.join(params)}) AS $$\n"
            f"BEGIN\n"
            f"    UPDATE {self.quote_identifier(meta.table_name)} SET {', '.join(updates)}\n"
            f"    WHERE {self.quote_identifier(meta.id_column.name)} = p_{meta.id_column.name};\n"
            f"END;\n"
            f"$$ LANGUAGE plpgsql;"
        )
        return [sql]

    def generate_delete_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_delete"
        id_type = self._get_proc_param_type(meta.id_column)
        sql = (
            f"CREATE OR REPLACE PROCEDURE {proc_name}(IN p_{meta.id_column.name} {id_type}) AS $$\n"
            f"BEGIN\n"
            f"    DELETE FROM {self.quote_identifier(meta.table_name)}\n"
            f"    WHERE {self.quote_identifier(meta.id_column.name)} = p_{meta.id_column.name};\n"
            f"END;\n"
            f"$$ LANGUAGE plpgsql;"
        )
        return [sql]

    def generate_get_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_get"
        params = [f"INOUT p_{meta.id_column.name} {self._get_proc_param_type(meta.id_column)}"]
        for col in meta.columns:
            if col.primary_key:
                continue
            params.append(f"INOUT p_{col.name} {self._get_proc_param_type(col)}")

        select_cols = [self.quote_identifier(c.name) for c in meta.columns if not c.primary_key]
        into_vars = [f"p_{c.name}" for c in meta.columns if not c.primary_key]

        sql = (
            f"CREATE OR REPLACE PROCEDURE {proc_name}({', '.join(params)}) AS $$\n"
            f"BEGIN\n"
            f"    SELECT {', '.join(select_cols)} INTO {', '.join(into_vars)}\n"
            f"    FROM {self.quote_identifier(meta.table_name)}\n"
            f"    WHERE {self.quote_identifier(meta.id_column.name)} = p_{meta.id_column.name};\n"
            f"    IF NOT FOUND THEN\n"
            f"        p_{meta.id_column.name} := NULL;\n"
            f"    END IF;\n"
            f"END;\n"
            f"$$ LANGUAGE plpgsql;"
        )
        return [sql]

    def generate_batch_insert_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_batch_insert"
        params = []
        if not meta.id_column.generated:
            params.append(f"IN p_{meta.id_column.name}s {self._get_proc_param_type(meta.id_column)}[]")
        for col in meta.columns:
            if col.primary_key:
                continue
            params.append(f"IN p_{col.name}s {self._get_proc_param_type(col)}[]")

        cols = []
        unnest_args = []
        if not meta.id_column.generated:
            cols.append(self.quote_identifier(meta.id_column.name))
            unnest_args.append(f"p_{meta.id_column.name}s")
        for col in meta.columns:
            if col.primary_key:
                continue
            cols.append(self.quote_identifier(col.name))
            unnest_args.append(f"p_{col.name}s")

        sql = (
            f"CREATE OR REPLACE PROCEDURE {proc_name}({', '.join(params)}) AS $$\n"
            f"BEGIN\n"
            f"    INSERT INTO {self.quote_identifier(meta.table_name)} ({', '.join(cols)})\n"
            f"    SELECT * FROM unnest({', '.join(unnest_args)});\n"
            f"END;\n"
            f"$$ LANGUAGE plpgsql;"
        )
        return [sql]

    def get_insert_call_statement(self, meta) -> str:
        count = len(meta.columns)
        return f"CALL sp_{meta.table_name}_insert({self.get_placeholders(count)})"

    def get_update_call_statement(self, meta) -> str:
        count = len(meta.columns)
        return f"CALL sp_{meta.table_name}_update({self.get_placeholders(count)})"

    def get_delete_call_statement(self, meta) -> str:
        return f"CALL sp_{meta.table_name}_delete(?)"

    def get_get_call_statement(self, meta) -> str:
        count = len(meta.columns)
        return f"CALL sp_{meta.table_name}_get({self.get_placeholders(count)})"

    def get_batch_insert_call_statement(self, meta) -> str:
        count = len(meta.columns) - 1 if meta.id_column.generated else len(meta.columns)
        return f"CALL sp_{meta.table_name}_batch_insert({self.get_placeholders(count)})"

    def paginate(self, sql: str, limit: int, offset: int) -> str:
        return f"{sql} LIMIT {limit} OFFSET {offset}"

    def quote_identifier(self, name: str) -> str:
        return f'"{name}"'

    def get_placeholders(self, count: int) -> str:
        return ",".join(["%s"] * count)

    def table_exists(self, conn, table_name: str) -> bool:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = %s)",
                (table_name.lower(),)
            )
            return cur.fetchone()[0]

    def procedure_exists(self, conn, procedure_name: str) -> bool:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT EXISTS (SELECT FROM pg_proc WHERE proname = %s)",
                (procedure_name.lower(),)
            )
            return cur.fetchone()[0]


class MySQLDialect(Dialect):
    supports_procedures = True

    def get_name(self) -> str:
        return "MySQL"

    def _get_sql_type(self, col) -> str:
        if col.encrypted:
            return "VARCHAR(1000)"
        t = col.field_type
        if t == str:
            return f"VARCHAR({col.length})"
        elif t == int:
            return "BIGINT" if col.primary_key else "INT"
        elif t == float:
            return "DOUBLE"
        elif t == bool:
            return "BOOLEAN"
        return "VARCHAR(255)"

    def _get_proc_param_type(self, col) -> str:
        return self._get_sql_type(col)

    def generate_create_table(self, meta) -> str:
        cols = []
        for col in meta.columns:
            col_def = f"{self.quote_identifier(col.name)} {self._get_sql_type(col)}"
            if col.primary_key:
                col_def += " PRIMARY KEY"
                if col.generated:
                    col_def += " AUTO_INCREMENT"
            else:
                if not col.nullable:
                    col_def += " NOT NULL"
                if col.unique:
                    col_def += " UNIQUE"
            cols.append(col_def)
        return f"CREATE TABLE IF NOT EXISTS {self.quote_identifier(meta.table_name)} ({', '.join(cols)})"

    def generate_create_index(self, table_name: str, column_name: str, index_name: str, unique: bool) -> str:
        uniq_str = "UNIQUE " if unique else ""
        return f"CREATE {uniq_str}INDEX {self.quote_identifier(index_name)} ON {self.quote_identifier(table_name)} ({self.quote_identifier(column_name)})"

    def generate_insert_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_insert"
        params = []
        id_col = meta.id_column
        if id_col.generated:
            params.append(f"OUT p_{id_col.name} {self._get_proc_param_type(id_col)}")
        else:
            params.append(f"IN p_{id_col.name} {self._get_proc_param_type(id_col)}")

        for col in meta.columns:
            if col.primary_key:
                continue
            params.append(f"IN p_{col.name} {self._get_proc_param_type(col)}")

        cols = []
        vals = []
        if not id_col.generated:
            cols.append(self.quote_identifier(id_col.name))
            vals.append(f"p_{id_col.name}")
        for col in meta.columns:
            if col.primary_key:
                continue
            cols.append(self.quote_identifier(col.name))
            vals.append(f"p_{col.name}")

        body = (
            f"INSERT INTO {self.quote_identifier(meta.table_name)} ({', '.join(cols)})\n"
            f"    VALUES ({', '.join(vals)});"
        )
        if id_col.generated:
            body += f"\n    SET p_{id_col.name} = LAST_INSERT_ID();"

        sql = (
            f"CREATE PROCEDURE {proc_name}({', '.join(params)})\n"
            f"BEGIN\n"
            f"    {body}\n"
            f"END"
        )
        return [f"DROP PROCEDURE IF EXISTS {proc_name}", sql]

    def generate_update_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_update"
        params = [f"IN p_{meta.id_column.name} {self._get_proc_param_type(meta.id_column)}"]
        for col in meta.columns:
            if col.primary_key:
                continue
            params.append(f"IN p_{col.name} {self._get_proc_param_type(col)}")

        updates = []
        for col in meta.columns:
            if col.primary_key:
                continue
            updates.append(f"{self.quote_identifier(col.name)} = p_{col.name}")

        sql = (
            f"CREATE PROCEDURE {proc_name}({', '.join(params)})\n"
            f"BEGIN\n"
            f"    UPDATE {self.quote_identifier(meta.table_name)} SET {', '.join(updates)}\n"
            f"    WHERE {self.quote_identifier(meta.id_column.name)} = p_{meta.id_column.name};\n"
            f"END"
        )
        return [f"DROP PROCEDURE IF EXISTS {proc_name}", sql]

    def generate_delete_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_delete"
        sql = (
            f"CREATE PROCEDURE {proc_name}(IN p_{meta.id_column.name} {self._get_proc_param_type(meta.id_column)})\n"
            f"BEGIN\n"
            f"    DELETE FROM {self.quote_identifier(meta.table_name)} WHERE {self.quote_identifier(meta.id_column.name)} = p_{meta.id_column.name};\n"
            f"END"
        )
        return [f"DROP PROCEDURE IF EXISTS {proc_name}", sql]

    def generate_get_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_get"
        sql = (
            f"CREATE PROCEDURE {proc_name}(IN p_{meta.id_column.name} {self._get_proc_param_type(meta.id_column)})\n"
            f"BEGIN\n"
            f"    SELECT * FROM {self.quote_identifier(meta.table_name)} WHERE {self.quote_identifier(meta.id_column.name)} = p_{meta.id_column.name};\n"
            f"END"
        )
        return [f"DROP PROCEDURE IF EXISTS {proc_name}", sql]

    def generate_batch_insert_procedure(self, meta) -> list:
        proc_name = f"sp_{meta.table_name}_batch_insert"
        sql = (
            f"CREATE PROCEDURE {proc_name}(IN p_json_data JSON)\n"
            f"BEGIN\n"
            f"    SELECT 1;\n"
            f"END"
        )
        return [f"DROP PROCEDURE IF EXISTS {proc_name}", sql]

    def get_insert_call_statement(self, meta) -> str:
        count = len(meta.columns)
        return f"CALL sp_{meta.table_name}_insert({self.get_placeholders(count)})"

    def get_update_call_statement(self, meta) -> str:
        count = len(meta.columns)
        return f"CALL sp_{meta.table_name}_update({self.get_placeholders(count)})"

    def get_delete_call_statement(self, meta) -> str:
        return f"CALL sp_{meta.table_name}_delete(?)"

    def get_get_call_statement(self, meta) -> str:
        return f"CALL sp_{meta.table_name}_get(?)"

    def get_batch_insert_call_statement(self, meta) -> str:
        return f"CALL sp_{meta.table_name}_batch_insert(?)"

    def paginate(self, sql: str, limit: int, offset: int) -> str:
        return f"{sql} LIMIT {limit} OFFSET {offset}"

    def quote_identifier(self, name: str) -> str:
        return f"`{name}`"

    def get_placeholders(self, count: int) -> str:
        return ",".join(["%s"] * count)

    def table_exists(self, conn, table_name: str) -> bool:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = %s",
                (table_name,)
            )
            return cur.fetchone()[0] > 0

    def procedure_exists(self, conn, procedure_name: str) -> bool:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) FROM information_schema.routines WHERE routine_schema = DATABASE() AND routine_name = %s",
                (procedure_name,)
            )
            return cur.fetchone()[0] > 0


class SQLiteDialect(Dialect):
    supports_procedures = False

    def get_name(self) -> str:
        return "SQLite"

    def _get_sql_type(self, col) -> str:
        if col.encrypted:
            return "TEXT"
        t = col.field_type
        if t == str:
            return "TEXT"
        elif t == int:
            return "INTEGER"
        elif t == float:
            return "REAL"
        elif t == bool:
            return "INTEGER"
        return "TEXT"

    def generate_create_table(self, meta) -> str:
        cols = []
        for col in meta.columns:
            col_def = f"{self.quote_identifier(col.name)} {self._get_sql_type(col)}"
            if col.primary_key:
                col_def += " PRIMARY KEY"
                if col.generated:
                    col_def += " AUTOINCREMENT"
            else:
                if not col.nullable:
                    col_def += " NOT NULL"
                if col.unique:
                    col_def += " UNIQUE"
            cols.append(col_def)
        return f"CREATE TABLE IF NOT EXISTS {self.quote_identifier(meta.table_name)} ({', '.join(cols)})"

    def generate_create_index(self, table_name: str, column_name: str, index_name: str, unique: bool) -> str:
        uniq_str = "UNIQUE " if unique else ""
        return f"CREATE {uniq_str}INDEX IF NOT EXISTS {self.quote_identifier(index_name)} ON {self.quote_identifier(table_name)} ({self.quote_identifier(column_name)})"

    def get_insert_call_statement(self, meta) -> str:
        id_col = meta.id_column
        cols = []
        if not id_col.generated:
            cols.append(self.quote_identifier(id_col.name))
        for col in meta.columns:
            if col.primary_key:
                continue
            cols.append(self.quote_identifier(col.name))
        placeholders = ",".join([f":{col.strip('`\"')}" for col in cols])
        return f"INSERT INTO {self.quote_identifier(meta.table_name)} ({', '.join(cols)}) VALUES ({placeholders})"

    def get_update_call_statement(self, meta) -> str:
        updates = []
        for col in meta.columns:
            if col.primary_key:
                continue
            name = col.name.strip('`\"')
            updates.append(f"{self.quote_identifier(col.name)} = :{name}")
        id_name = meta.id_column.name.strip('`\"')
        return f"UPDATE {self.quote_identifier(meta.table_name)} SET {', '.join(updates)} WHERE {self.quote_identifier(meta.id_column.name)} = :{id_name}"

    def get_delete_call_statement(self, meta) -> str:
        id_name = meta.id_column.name.strip('`\"')
        return f"DELETE FROM {self.quote_identifier(meta.table_name)} WHERE {self.quote_identifier(meta.id_column.name)} = :{id_name}"

    def get_get_call_statement(self, meta) -> str:
        id_name = meta.id_column.name.strip('`\"')
        return f"SELECT * FROM {self.quote_identifier(meta.table_name)} WHERE {self.quote_identifier(meta.id_column.name)} = :{id_name}"

    def get_batch_insert_call_statement(self, meta) -> str:
        return self.get_insert_call_statement(meta)

    def paginate(self, sql: str, limit: int, offset: int) -> str:
        return f"{sql} LIMIT {limit} OFFSET {offset}"

    def quote_identifier(self, name: str) -> str:
        return f'"{name}"'

    def table_exists(self, conn, table_name: str) -> bool:
        cur = conn.cursor()
        cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
            (table_name,)
        )
        res = cur.fetchone()
        return res is not None
